### ISSUE TITLE
Create /opt/savapage directory

### ISSUE THREAD

**Issue by robbosch** [gsanchietti/nethserver-savapage#1]
I don't see the creation of the /opt/savapage directory. But the savapage user does get permissions on this directory. Am I missing something here?

**Comment by gsanchietti** [comment]
We need to add the **-m** switch to the command for creating the user.

I didn't create it because I'm not sure what are the required permission on the directory.

**Comment by gsanchietti** [comment]
Now the spec explode all savapage files inside /opt/savapage with correct permission.

Check out this RPM in nethforge-testing:
nethserver-savapage-0.0.1-1.7.g10a20cc.ns7.x86_64.rpm

The install part of SavaPage is still missing.
